version: '3.4'

services:
  sd:
    image: sd
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
        - "8081:3000"
    expose:
        - 8081
    command: ["npm", "start"]
    restart: always 
    stdin_open: true 